# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 13:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatPageMetaTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=150)),
                (
                    "flatpage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_tag_set",
                        to="flatpages.FlatPage",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Meta tag",
            },
        ),
        migrations.CreateModel(
            name="MetaTagType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("format_string", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("allow_multiple", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SiteMetaTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=150)),
                (
                    "meta_tag_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flatpage_meta_sitemetatag_related",
                        to="flatpage_meta.MetaTagType",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_tag_set",
                        to="sites.Site",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Meta tag",
            },
        ),
        migrations.AddField(
            model_name="flatpagemetatag",
            name="meta_tag_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flatpage_meta_flatpagemetatag_related",
                to="flatpage_meta.MetaTagType",
            ),
        ),
    ]
